/* Generated by tools/rules/consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/itit/rules/constants.
   The lifted ones are in delta_consts_itit.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t itit_evv_authored_data[] = {
    /* fence_03, 1 bytes at 0 */
    3,
    /* lts_bb, 2 bytes at 1 */
    11,11,
    /* say_0101, 2 bytes at 3 */
    1,1,
    /* say_01, 1 bytes at 5 */
    1,
    /* lts_dd, 2 bytes at 6 */
    13,13,
    /* say_0303, 2 bytes at 8 */
    3,3,
    /* lts_ff, 2 bytes at 10 */
    14,14,
    /* say_0808, 2 bytes at 12 */
    8,8,
    /* say_08, 1 bytes at 14 */
    8,
    /* lts_pp, 2 bytes at 15 */
    22,22,
    /* say_0202, 2 bytes at 17 */
    2,2,
    /* say_02, 1 bytes at 19 */
    2,
    /* lts_tt, 2 bytes at 20 */
    26,26,
    /* say_0404, 2 bytes at 22 */
    4,4,
    /* say_04, 1 bytes at 24 */
    4,
    /* lts_vv, 2 bytes at 25 */
    27,27,
    /* say_0707, 2 bytes at 27 */
    7,7,
    /* say_07, 1 bytes at 29 */
    7,
    /* lts_rr, 2 bytes at 30 */
    24,24,
    /* say_16, 1 bytes at 32 */
    22,
    /* say_15, 1 bytes at 33 */
    21,
    /* say_0d, 1 bytes at 34 */
    13,
    /* say_05, 1 bytes at 35 */
    5,
    /* say_050a, 2 bytes at 36 */
    5,10,
    /* say_1e, 1 bytes at 38 */
    30,
    /* lts_ll, 2 bytes at 39 */
    19,19,
    /* say_1717, 2 bytes at 41 */
    23,23,
    /* say_17, 1 bytes at 43 */
    23,
    /* lts_mm, 2 bytes at 44 */
    20,20,
    /* say_1111, 2 bytes at 46 */
    17,17,
    /* say_11, 1 bytes at 48 */
    17,
    /* lts_nn, 2 bytes at 49 */
    21,21,
    /* say_1212, 2 bytes at 51 */
    18,18,
    /* lts_ce, 2 bytes at 53 */
    12,2,
    /* say_12, 1 bytes at 55 */
    18,
    /* lts_ci, 2 bytes at 56 */
    12,3,
    /* lts_ge, 2 bytes at 58 */
    15,2,
    /* lts_gi, 2 bytes at 60 */
    15,3,
    /* lts_c, 1 bytes at 62 */
    12,
    /* say_14, 1 bytes at 63 */
    20,
    /* lts_g, 1 bytes at 64 */
    15,
    /* lts_cch, 3 bytes at 65 */
    12,12,16,
    /* say_0505, 2 bytes at 68 */
    5,5,
    /* lts_cc, 2 bytes at 70 */
    12,12,
    /* say_040e, 2 bytes at 72 */
    4,14,
    /* lts_cci, 3 bytes at 74 */
    12,12,3,
    /* lts_62, 1 bytes at 77 */
    98,
    /* lts_6c, 1 bytes at 78 */
    108,
    /* lts_63, 1 bytes at 79 */
    99,
    /* lts_6d, 1 bytes at 80 */
    109,
    /* lts_ch, 2 bytes at 81 */
    12,16,
    /* lts_ck, 2 bytes at 83 */
    12,18,
    /* say_0e, 1 bytes at 85 */
    14,
    /* lts_ss, 2 bytes at 86 */
    25,25,
    /* say_0a0a, 2 bytes at 88 */
    10,10,
    /* lts_sh, 2 bytes at 90 */
    25,16,
    /* lts_sc, 2 bytes at 92 */
    25,12,
    /* lts_sciatica, 8 bytes at 94 */
    25,12,3,1,26,3,12,1,
    /* lts_sciatto, 7 bytes at 102 */
    25,12,3,1,26,26,4,
    /* lts_sci, 3 bytes at 109 */
    25,12,3,
    /* lts_scia, 4 bytes at 112 */
    25,12,3,1,
    /* lts_sciamo, 6 bytes at 116 */
    25,12,3,1,20,4,
    /* lts_sciano, 6 bytes at 122 */
    25,12,3,1,21,4,
    /* lts_sciare, 6 bytes at 128 */
    25,12,3,1,24,2,
    /* lts_scie, 4 bytes at 134 */
    25,12,3,2,
    /* lts_scio, 4 bytes at 138 */
    25,12,3,4,
    /* say_0c1b, 2 bytes at 142 */
    12,27,
    /* lts_sciat, 5 bytes at 144 */
    25,12,3,1,26,
    /* lts_sciav, 5 bytes at 149 */
    25,12,3,1,27,
    /* lts_scier, 5 bytes at 154 */
    25,12,3,2,24,
    /* lts_b, 1 bytes at 159 */
    11,
    /* say_09, 1 bytes at 160 */
    9,
    /* lts_l, 1 bytes at 161 */
    19,
    /* lts_r, 1 bytes at 162 */
    24,
    /* lts_v, 1 bytes at 163 */
    27,
    /* lts_aseps, 5 bytes at 164 */
    1,25,2,22,25,
    /* lts_asim, 4 bytes at 169 */
    1,25,3,20,
    /* lts_casori, 6 bytes at 173 */
    12,1,25,4,24,3,
    /* lts_dinosaur, 8 bytes at 179 */
    13,3,21,4,25,1,5,24,
    /* lts_girasol, 7 bytes at 187 */
    15,3,24,1,25,4,19,
    /* lts_rosic, 5 bytes at 194 */
    24,4,25,3,12,
    /* lts_staser, 6 bytes at 199 */
    25,26,1,25,2,24,
    /* say_0a, 1 bytes at 205 */
    10,
    /* lts_gg, 2 bytes at 206 */
    15,15,
    /* say_030d, 2 bytes at 208 */
    3,13,
    /* lts_ggi, 3 bytes at 210 */
    15,15,3,
    /* say_0606, 2 bytes at 213 */
    6,6,
    /* lts_gh, 2 bytes at 215 */
    15,16,
    /* say_06, 1 bytes at 217 */
    6,
    /* lts_gli, 3 bytes at 218 */
    15,19,3,
    /* say_06171b, 3 bytes at 221 */
    6,23,27,
    /* lts_negligent, 9 bytes at 224 */
    21,2,15,19,3,15,2,21,26,
    /* lts_gl, 2 bytes at 233 */
    15,19,
    /* lts_gn, 2 bytes at 235 */
    15,21,
    /* lts_elogi, 5 bytes at 237 */
    2,19,4,15,3,
    /* lts_orologi, 7 bytes at 242 */
    4,24,4,19,4,15,3,
    /* lts_murgi, 5 bytes at 249 */
    20,5,24,15,3,
    /* lts_ol, 2 bytes at 254 */
    4,19,
    /* say_0d1b, 2 bytes at 256 */
    13,27,
    /* lts_ru, 2 bytes at 258 */
    24,5,
    /* lts_austriac, 8 bytes at 260 */
    1,5,25,26,24,3,1,12,
    /* lts_autonom, 7 bytes at 268 */
    1,5,26,4,21,4,20,
    /* lts_autopsi, 7 bytes at 275 */
    1,5,26,4,22,25,3,
    /* lts_abbazi, 6 bytes at 282 */
    1,11,11,1,31,3,
    /* lts_addi, 4 bytes at 288 */
    1,13,13,3,
    /* lts_agenzi, 6 bytes at 292 */
    1,15,2,21,31,3,
    /* lts_agoni, 5 bytes at 298 */
    1,15,4,21,3,
    /* lts_albani, 6 bytes at 303 */
    1,19,11,1,21,3,
    /* lts_allegri, 7 bytes at 309 */
    1,19,19,2,15,24,3,
    /* lts_allergi, 7 bytes at 316 */
    1,19,19,2,24,15,3,
    /* lts_amnisti, 7 bytes at 323 */
    1,20,21,3,25,26,3,
    /* lts_anatomi, 7 bytes at 330 */
    1,21,1,26,4,20,3,
    /* lts_anomali, 7 bytes at 337 */
    1,21,4,20,1,19,3,
    /* lts_andrein, 7 bytes at 344 */
    1,21,13,24,2,3,21,
    /* lts_antipati, 8 bytes at 351 */
    1,21,26,3,22,1,26,3,
    /* lts_appendicectomi, 14 bytes at 359 */
    1,22,22,2,21,13,3,12,2,12,26,4,20,3,
    /* lts_armeri, 6 bytes at 373 */
    1,24,20,2,24,3,
    /* lts_armoni, 6 bytes at 379 */
    1,24,20,4,21,3,
    /* lts_asfissi, 7 bytes at 385 */
    1,25,14,3,25,25,3,
    /* lts_assenteism, 10 bytes at 392 */
    1,25,25,2,21,26,2,3,25,20,
    /* lts_avari, 5 bytes at 402 */
    1,27,1,24,3,
    /* lts_avvi, 4 bytes at 407 */
    1,27,27,3,
    /* lts_eutanasi, 8 bytes at 411 */
    2,5,26,1,21,1,25,3,
    /* lts_ebraic, 6 bytes at 419 */
    2,11,24,1,3,12,
    /* lts_editori, 7 bytes at 425 */
    2,13,3,26,4,24,3,
    /* lts_egemoni, 7 bytes at 432 */
    2,15,2,20,4,21,3,
    /* lts_emorragi, 8 bytes at 439 */
    2,20,4,24,24,1,15,3,
    /* lts_energi, 6 bytes at 447 */
    2,21,2,24,15,3,
    /* lts_enciclopedi, 11 bytes at 453 */
    2,21,12,3,12,19,4,22,2,13,3,
    /* lts_epidemi, 7 bytes at 464 */
    2,22,3,13,2,20,3,
    /* lts_epifani, 7 bytes at 471 */
    2,22,3,14,1,21,3,
    /* lts_eresi, 5 bytes at 478 */
    2,24,2,25,3,
    /* lts_eroin, 5 bytes at 483 */
    2,24,4,3,21,
    /* lts_esattori, 8 bytes at 488 */
    2,25,1,26,26,4,24,3,
    /* lts_impreditori, 11 bytes at 496 */
    3,20,22,24,2,13,3,26,4,24,3,
    /* lts_invi, 4 bytes at 507 */
    3,21,27,3,
    /* lts_ipocrisi, 8 bytes at 511 */
    3,22,4,12,24,3,25,3,
    /* lts_ironi, 5 bytes at 519 */
    3,24,4,21,3,
    /* lts_obli, 4 bytes at 524 */
    4,11,19,3,
    /* lts_olimpiad, 8 bytes at 528 */
    4,19,3,20,22,3,1,13,
    /* lts_omeli, 5 bytes at 536 */
    4,20,2,19,3,
    /* lts_ortodossi, 9 bytes at 541 */
    4,24,26,4,13,4,25,25,3,
    /* lts_ortopedi, 8 bytes at 550 */
    4,24,26,4,22,2,13,3,
    /* lts_ossi, 4 bytes at 558 */
    4,25,25,3,
    /* lts_utopi, 5 bytes at 562 */
    5,26,4,22,3,
    /* lts_bali, 4 bytes at 567 */
    11,1,19,3,
    /* lts_batteri, 7 bytes at 571 */
    11,1,26,26,2,24,3,
    /* lts_bavari, 6 bytes at 578 */
    11,1,27,1,24,3,
    /* lts_beccari, 7 bytes at 584 */
    11,2,12,12,1,24,3,
    /* lts_borghesi, 8 bytes at 591 */
    11,4,24,15,16,2,25,3,
    /* lts_bugi, 4 bytes at 599 */
    11,5,15,3,
    /* lts_bulgari, 7 bytes at 603 */
    11,5,19,15,1,24,3,
    /* lts_calori, 6 bytes at 610 */
    12,1,19,4,24,3,
    /* lts_categori, 8 bytes at 616 */
    12,1,26,2,15,4,24,3,
    /* lts_cavalcavi, 9 bytes at 624 */
    12,1,27,1,19,12,1,27,3,
    /* lts_cocain, 6 bytes at 633 */
    12,4,12,1,3,21,
    /* lts_compagni, 8 bytes at 639 */
    12,4,20,22,1,15,21,3,
    /* lts_corridoi, 8 bytes at 647 */
    12,4,24,24,3,13,4,3,
    /* lts_corsi, 5 bytes at 655 */
    12,4,24,25,3,
    /* lts_cortesi, 7 bytes at 660 */
    12,4,24,26,2,25,3,
    /* lts_chichibio, 9 bytes at 667 */
    12,16,3,12,16,3,11,3,4,
    /* lts_chilocalori, 11 bytes at 676 */
    12,16,3,19,4,12,1,19,4,24,3,
    /* lts_croceri, 7 bytes at 687 */
    12,24,4,12,2,24,3,
    /* lts_deific, 6 bytes at 694 */
    13,2,3,14,3,12,
    /* lts_demagogi, 8 bytes at 700 */
    13,2,20,1,15,4,15,3,
    /* lts_detraibil, 9 bytes at 708 */
    13,2,26,24,1,3,11,3,19,
    /* lts_devi, 4 bytes at 717 */
    13,2,27,3,
    /* lts_dio, 3 bytes at 721 */
    13,3,4,
    /* lts_didascali, 9 bytes at 724 */
    13,3,13,1,25,12,1,19,3,
    /* lts_dinasti, 7 bytes at 733 */
    13,3,21,1,25,26,3,
    /* lts_diplomazi, 9 bytes at 740 */
    13,3,22,19,4,20,1,31,3,
    /* lts_fantasi, 7 bytes at 749 */
    14,1,21,26,1,25,3,
    /* lts_farmaci, 7 bytes at 756 */
    14,1,24,20,1,12,3,
    /* lts_fattori, 7 bytes at 763 */
    14,1,26,26,4,24,3,
    /* lts_ferrovi, 7 bytes at 770 */
    14,2,24,24,4,27,3,
    /* lts_filosofi, 8 bytes at 777 */
    14,3,19,4,25,4,14,3,
    /* lts_folli, 5 bytes at 785 */
    14,4,19,19,3,
    /* lts_fosch, 5 bytes at 790 */
    14,4,25,12,16,
    /* lts_funivi, 6 bytes at 795 */
    14,5,21,3,27,3,
    /* lts_frusci, 6 bytes at 801 */
    14,24,5,25,12,3,
    /* lts_gabriel, 7 bytes at 807 */
    15,1,11,24,3,2,19,
    /* lts_garanzi, 7 bytes at 814 */
    15,1,24,1,21,31,3,
    /* lts_garzi, 5 bytes at 821 */
    15,1,24,31,3,
    /* lts_gelosi, 6 bytes at 826 */
    15,2,19,4,25,3,
    /* lts_gerarchi, 8 bytes at 832 */
    15,2,24,1,24,12,16,3,
    /* lts_giuri, 5 bytes at 840 */
    15,3,5,24,3,
    /* lts_lauri, 5 bytes at 845 */
    19,1,5,24,3,
    /* lts_leucemi, 7 bytes at 850 */
    19,2,5,12,2,20,3,
    /* lts_liut, 4 bytes at 857 */
    19,3,5,26,
    /* lts_logori, 6 bytes at 861 */
    19,4,15,4,24,3,
    /* lts_lombardi, 8 bytes at 867 */
    19,4,20,11,1,24,13,3,
    /* lts_maestri, 7 bytes at 875 */
    20,1,2,25,26,24,3,
    /* lts_magi, 4 bytes at 882 */
    20,1,15,3,
    /* lts_malatti, 7 bytes at 886 */
    20,1,19,1,26,26,3,
    /* lts_malinconi, 9 bytes at 893 */
    20,1,19,3,21,12,4,21,3,
    /* lts_mani, 4 bytes at 902 */
    20,1,21,3,
    /* lts_melodi, 6 bytes at 906 */
    20,2,19,4,13,3,
    /* lts_messi, 5 bytes at 912 */
    20,2,25,25,3,
    /* lts_mezzadri, 8 bytes at 917 */
    20,2,31,31,1,13,24,3,
    /* lts_miop, 4 bytes at 925 */
    20,3,4,22,
    /* lts_miopi, 5 bytes at 929 */
    20,3,4,22,3,
    /* lts_migliori, 8 bytes at 934 */
    20,3,15,19,3,4,24,3,
    /* lts_miriad, 6 bytes at 942 */
    20,3,24,3,1,13,
    /* lts_monarchi, 8 bytes at 948 */
    20,4,21,1,24,12,16,3,
    /* lts_mormori, 7 bytes at 956 */
    20,4,24,20,4,24,3,
    /* lts_mosaic, 6 bytes at 963 */
    20,4,25,1,3,12,
    /* lts_nicosi, 6 bytes at 969 */
    21,3,12,4,25,3,
    /* lts_nostalgi, 8 bytes at 975 */
    21,4,25,26,1,19,15,3,
    /* lts_parodi, 6 bytes at 983 */
    22,1,24,4,13,3,
    /* lts_pavi, 4 bytes at 989 */
    22,1,27,3,
    /* lts_pazzi, 5 bytes at 993 */
    22,1,31,31,3,
    /* lts_pendi, 5 bytes at 998 */
    22,2,21,13,3,
    /* lts_period, 6 bytes at 1003 */
    22,2,24,3,4,13,
    /* lts_piol, 4 bytes at 1009 */
    22,3,4,19,
    /* lts_poesi, 5 bytes at 1013 */
    22,4,2,25,3,
    /* lts_polizi, 6 bytes at 1018 */
    22,4,19,3,31,3,
    /* lts_pulizi, 6 bytes at 1024 */
    22,5,19,3,31,3,
    /* lts_prigioni, 8 bytes at 1030 */
    22,24,3,15,3,4,21,3,
    /* lts_proib, 5 bytes at 1038 */
    22,24,4,3,11,
    /* lts_probatori, 9 bytes at 1043 */
    22,24,4,11,1,26,4,24,3,
    /* lts_protein, 7 bytes at 1052 */
    22,24,4,26,2,3,21,
    /* lts_psichiatri, 10 bytes at 1059 */
    22,25,3,12,16,3,1,26,24,3,
    /* lts_qualsias, 8 bytes at 1069 */
    23,5,1,19,25,3,1,25,
    /* lts_rapsodi, 7 bytes at 1077 */
    24,1,22,25,4,13,3,
    /* lts_retrovi, 7 bytes at 1084 */
    24,2,26,24,4,27,3,
    /* lts_ricevitori, 10 bytes at 1091 */
    24,3,12,2,27,3,26,4,24,3,
    /* lts_rinvi, 5 bytes at 1101 */
    24,3,21,27,3,
    /* lts_romani, 6 bytes at 1106 */
    24,4,20,1,21,3,
    /* lts_ronzi, 5 bytes at 1112 */
    24,4,21,31,3,
    /* lts_rosoli, 6 bytes at 1117 */
    24,4,25,4,19,3,
    /* lts_sartori, 7 bytes at 1123 */
    25,1,24,26,4,24,3,
    /* lts_simpati, 7 bytes at 1130 */
    25,3,20,22,1,26,3,
    /* lts_sinergi, 7 bytes at 1137 */
    25,3,21,2,24,15,3,
    /* lts_sincroni, 8 bytes at 1144 */
    25,3,21,12,24,4,21,3,
    /* lts_sinfoni, 7 bytes at 1152 */
    25,3,21,14,4,21,3,
    /* lts_sintoni, 7 bytes at 1159 */
    25,3,21,26,4,21,3,
    /* lts_sofi, 4 bytes at 1166 */
    25,4,14,3,
    /* lts_suic, 4 bytes at 1170 */
    25,5,3,12,
    /* lts_suin, 4 bytes at 1174 */
    25,5,3,21,
    /* lts_supremazi, 9 bytes at 1178 */
    25,5,22,24,2,20,1,31,3,
    /* lts_scali, 5 bytes at 1187 */
    25,12,1,19,3,
    /* lts_scrivani, 8 bytes at 1192 */
    25,12,24,3,27,1,21,3,
    /* lts_sfolgori, 8 bytes at 1200 */
    25,14,4,19,15,4,24,3,
    /* lts_spiam, 5 bytes at 1208 */
    25,22,3,1,20,
    /* lts_spiar, 5 bytes at 1213 */
    25,22,3,1,24,
    /* lts_spiat, 5 bytes at 1218 */
    25,22,3,1,26,
    /* lts_spion, 5 bytes at 1223 */
    25,22,3,4,21,
    /* lts_stereofoni, 10 bytes at 1228 */
    25,26,2,24,2,4,14,4,21,3,
    /* lts_strategi, 8 bytes at 1238 */
    25,26,24,1,26,2,15,3,
    /* lts_teori, 5 bytes at 1246 */
    26,2,4,24,3,
    /* lts_teleogi, 7 bytes at 1251 */
    26,2,19,2,4,15,3,
    /* lts_telefoni, 8 bytes at 1258 */
    26,2,19,2,14,4,21,3,
    /* lts_ticchetti, 9 bytes at 1266 */
    26,3,12,12,16,2,26,26,3,
    /* lts_tunisi, 6 bytes at 1275 */
    26,5,21,3,25,3,
    /* lts_turchi, 6 bytes at 1281 */
    26,5,24,12,16,3,
    /* lts_tuttavi, 7 bytes at 1287 */
    26,5,26,26,1,27,3,
    /* lts_veicol, 6 bytes at 1294 */
    27,2,3,12,4,19,
    /* lts_vial, 4 bytes at 1300 */
    27,3,1,19,
    /* lts_viol, 4 bytes at 1304 */
    27,3,4,19,
    /* lts_zootecni, 8 bytes at 1308 */
    31,4,4,26,2,12,21,3,
    /* lts_2501031a03, 5 bytes at 1316 */
    37,1,3,26,3,
    /* lts_3401031802, 5 bytes at 1321 */
    52,1,3,24,2,
    /* lts_regia, 5 bytes at 1326 */
    24,2,15,3,1,
    /* say_19, 1 bytes at 1331 */
    25,
    /* lts_aizz, 4 bytes at 1332 */
    1,3,31,31,
    /* lts_addrizz, 7 bytes at 1336 */
    1,13,13,24,3,31,31,
    /* lts_indirizz, 8 bytes at 1343 */
    3,21,13,3,24,3,31,31,
    /* lts_intirizz, 8 bytes at 1351 */
    3,21,26,3,24,3,31,31,
    /* lts_isvizz, 6 bytes at 1359 */
    3,25,27,3,31,31,
    /* lts_drizz, 5 bytes at 1365 */
    13,24,3,31,31,
    /* lts_frizz, 5 bytes at 1370 */
    14,24,3,31,31,
    /* lts_guizz, 5 bytes at 1375 */
    15,5,3,31,31,
    /* lts_lizz, 4 bytes at 1380 */
    19,3,31,31,
    /* lts_nizz, 4 bytes at 1384 */
    21,3,31,31,
    /* lts_pellizz, 7 bytes at 1388 */
    22,2,19,19,3,31,31,
    /* lts_pizz, 4 bytes at 1395 */
    22,3,31,31,
    /* lts_polizz, 6 bytes at 1399 */
    22,4,19,3,31,31,
    /* lts_raddrizz, 8 bytes at 1405 */
    24,1,13,13,24,3,31,31,
    /* lts_ravizz, 6 bytes at 1413 */
    24,1,27,3,31,31,
    /* lts_rizz, 4 bytes at 1419 */
    24,3,31,31,
    /* lts_schizz, 6 bytes at 1423 */
    25,12,16,3,31,31,
    /* lts_stizz, 5 bytes at 1429 */
    25,26,3,31,31,
    /* lts_strizz, 6 bytes at 1434 */
    25,26,24,3,31,31,
    /* lts_svizz, 5 bytes at 1440 */
    25,27,3,31,31,
    /* lts_zz, 2 bytes at 1445 */
    31,31,
    /* say_0410, 2 bytes at 1447 */
    4,16,
    /* lts_aguzzin, 7 bytes at 1449 */
    1,15,5,31,31,3,21,
    /* lts_amazzon, 7 bytes at 1456 */
    1,20,1,31,31,4,21,
    /* lts_azzard, 6 bytes at 1463 */
    1,31,31,1,24,13,
    /* lts_azzecc, 6 bytes at 1469 */
    1,31,31,2,12,12,
    /* lts_azzurr, 6 bytes at 1475 */
    1,31,31,5,24,24,
    /* lts_orizzont, 8 bytes at 1481 */
    4,24,3,31,31,4,21,26,
    /* lts_buzz, 4 bytes at 1489 */
    11,5,31,31,
    /* lts_dirozz, 6 bytes at 1493 */
    13,3,24,4,31,31,
    /* lts_dozzin, 6 bytes at 1499 */
    13,4,31,31,3,21,
    /* lts_frammezz, 8 bytes at 1505 */
    14,24,1,20,20,2,31,31,
    /* lts_gazz, 4 bytes at 1513 */
    15,1,31,31,
    /* lts_grezz, 5 bytes at 1517 */
    15,24,2,31,31,
    /* lts_magazzin, 8 bytes at 1522 */
    20,1,15,1,31,31,3,21,
    /* lts_mezz, 4 bytes at 1530 */
    20,2,31,31,
    /* lts_rozz, 4 bytes at 1534 */
    24,4,31,31,
    /* lts_zazzer, 6 bytes at 1538 */
    31,1,31,31,2,24,
    /* say_030f, 2 bytes at 1544 */
    3,15,
    /* lts_arzill, 6 bytes at 1546 */
    1,24,31,3,19,19,
    /* lts_inzacch, 7 bytes at 1552 */
    3,21,31,1,12,12,16,
    /* lts_inzupp, 6 bytes at 1559 */
    3,21,31,5,22,22,
    /* lts_balzac, 6 bytes at 1565 */
    11,1,19,31,1,12,
    /* lts_benz, 4 bytes at 1571 */
    11,2,21,31,
    /* lts_donz, 4 bytes at 1575 */
    13,4,21,31,
    /* lts_manzan, 6 bytes at 1579 */
    20,1,21,31,1,21,
    /* lts_penz, 4 bytes at 1585 */
    22,2,21,31,
    /* lts_verz, 4 bytes at 1589 */
    27,2,24,31,
    /* lts_zanz, 4 bytes at 1593 */
    31,1,21,31,
    /* lts_t, 1 bytes at 1597 */
    26,
    /* say_10, 1 bytes at 1598 */
    16,
    /* lts_nam, 3 bytes at 1599 */
    21,1,20,
    /* lts_nort, 4 bytes at 1602 */
    21,4,24,26,
    /* lts_nor, 3 bytes at 1606 */
    21,4,24,
    /* lts_rag, 3 bytes at 1609 */
    24,1,15,
    /* lts_iend, 4 bytes at 1612 */
    3,2,21,13,
    /* say_1f, 1 bytes at 1616 */
    31,
    /* lts_duole, 5 bytes at 1617 */
    13,5,4,19,2,
    /* lts_duoli, 5 bytes at 1622 */
    13,5,4,19,3,
    /* lts_duomo, 5 bytes at 1627 */
    13,5,4,20,4,
    /* lts_altrui, 6 bytes at 1632 */
    1,19,26,24,5,3,
    /* lts_ambedue, 7 bytes at 1638 */
    1,20,11,2,13,5,2,
    /* lts_ambidue, 7 bytes at 1645 */
    1,20,11,3,13,5,2,
    /* lts_intuit, 6 bytes at 1652 */
    3,21,26,5,3,26,
    /* lts_baul, 4 bytes at 1658 */
    11,1,5,19,
    /* lts_balau, 5 bytes at 1662 */
    11,1,19,1,5,
    /* lts_bue, 3 bytes at 1667 */
    11,5,2,
    /* lts_bui, 3 bytes at 1670 */
    11,5,3,
    /* lts_cadaun, 6 bytes at 1673 */
    12,1,13,1,5,21,
    /* lts_circuit, 7 bytes at 1679 */
    12,3,24,12,5,3,26,
    /* lts_deum, 4 bytes at 1686 */
    13,2,5,20,
    /* lts_due, 3 bytes at 1690 */
    13,5,2,
    /* lts_duo, 3 bytes at 1693 */
    13,5,4,
    /* lts_fortuit, 7 bytes at 1696 */
    14,4,24,26,5,3,26,
    /* lts_fui, 3 bytes at 1703 */
    14,5,3,
    /* lts_fluid, 5 bytes at 1706 */
    14,19,5,3,13,
    /* lts_fluttuante, 10 bytes at 1711 */
    14,19,5,26,26,5,1,21,26,2,
    /* lts_giand, 5 bytes at 1721 */
    15,3,1,21,13,
    /* lts_gratuit, 7 bytes at 1726 */
    15,24,1,26,5,3,26,
    /* lts_paur, 4 bytes at 1733 */
    22,1,5,24,
    /* lts_tedeum, 6 bytes at 1737 */
    26,2,13,2,5,20,
    /* lts_dia, 3 bytes at 1743 */
    13,3,1,
    /* lts_diagnosi, 8 bytes at 1746 */
    13,3,1,15,21,4,25,3,
    /* lts_diatriba, 8 bytes at 1754 */
    13,3,1,26,24,3,11,1,
    /* lts_diurno, 6 bytes at 1762 */
    13,3,5,24,21,4,
    /* lts_pia, 3 bytes at 1768 */
    22,3,1,
    /* lts_pio, 3 bytes at 1771 */
    22,3,4,
    /* lts_sia, 3 bytes at 1774 */
    25,3,1,
    /* lts_spia, 4 bytes at 1777 */
    25,22,3,1,
    /* lts_spiano, 6 bytes at 1781 */
    25,22,3,1,21,4,
    /* lts_spie, 4 bytes at 1787 */
    25,22,3,2,
    /* lts_spio, 4 bytes at 1791 */
    25,22,3,4,
    /* lts_trio, 4 bytes at 1795 */
    26,24,3,4,
    /* lts_zia, 3 bytes at 1799 */
    31,3,1,
    /* lts_zie, 3 bytes at 1802 */
    31,3,2,
    /* lts_zio, 3 bytes at 1805 */
    31,3,4,
    /* lts_avarizi, 7 bytes at 1808 */
    1,27,1,24,3,31,3,
    /* lts_invidi, 6 bytes at 1815 */
    3,21,27,3,13,3,
    /* lts_invischi, 8 bytes at 1821 */
    3,21,27,3,25,12,16,3,
    /* lts_ferroviari, 10 bytes at 1829 */
    14,2,24,24,4,27,3,1,24,3,
    /* lts_manicomi, 8 bytes at 1839 */
    20,1,21,3,12,4,20,3,
    /* lts_marinai, 7 bytes at 1847 */
    20,1,24,3,21,1,3,
    /* lts_arteri, 6 bytes at 1854 */
    1,24,26,2,24,3,
    /* lts_imperia, 7 bytes at 1860 */
    3,20,22,2,24,3,1,
    /* lts_feri, 4 bytes at 1867 */
    14,2,24,3,
    /* lts_maceri, 6 bytes at 1871 */
    20,1,12,2,24,3,
    /* lts_materi, 6 bytes at 1877 */
    20,1,26,2,24,3,
    /* lts_miseri, 6 bytes at 1883 */
    20,3,25,2,24,3,
    /* lts_seri, 4 bytes at 1889 */
    25,2,24,3,
    /* lts_siberi, 6 bytes at 1893 */
    25,3,11,2,24,3,
    /* lts_valeri, 6 bytes at 1899 */
    27,1,19,2,24,3,
    /* lts_zarc, 4 bytes at 1905 */
    31,1,24,12,
    /* lts_nof, 3 bytes at 1909 */
    21,4,14,
    /* lts_farg, 4 bytes at 1912 */
    14,1,24,15,
    /* lts_gol, 3 bytes at 1916 */
    15,4,19,
    /* lts_rtem, 4 bytes at 1919 */
    24,26,2,20,
    /* lts_mono, 4 bytes at 1923 */
    20,4,21,4,
    /* lts_paret, 5 bytes at 1927 */
    22,1,24,2,26,
    /* lts_re, 2 bytes at 1932 */
    24,2,
    /* lts_aco, 3 bytes at 1934 */
    1,12,4,
    /* lts_aca, 3 bytes at 1937 */
    1,12,1,
    /* lts_ach, 3 bytes at 1940 */
    1,12,16,
    /* lts_sm, 2 bytes at 1943 */
    25,20,
    /* lts_st, 2 bytes at 1945 */
    25,26,
};

const delta_store itit_delta_authored_store[] = {
    { itit_evv_authored_data, sizeof itit_evv_authored_data },
    { 0, 0 },
};
