/* Generated by tools/rules/consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/itit/rules/constants.
   The lifted ones are in delta_consts_itit.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t itit_evv_authored_data[] = {
    /* fence_03, 1 bytes at 0 */
    3,
    /* lts_bb, 2 bytes at 1 */
    11,11,
    /* say_0101, 2 bytes at 3 */
    1,1,
    /* say_01, 1 bytes at 5 */
    1,
    /* lts_dd, 2 bytes at 6 */
    13,13,
    /* say_0303, 2 bytes at 8 */
    3,3,
    /* lts_ff, 2 bytes at 10 */
    14,14,
    /* say_0808, 2 bytes at 12 */
    8,8,
    /* say_08, 1 bytes at 14 */
    8,
    /* lts_pp, 2 bytes at 15 */
    22,22,
    /* say_0202, 2 bytes at 17 */
    2,2,
    /* say_02, 1 bytes at 19 */
    2,
    /* lts_tt, 2 bytes at 20 */
    26,26,
    /* say_0404, 2 bytes at 22 */
    4,4,
    /* say_04, 1 bytes at 24 */
    4,
    /* lts_vv, 2 bytes at 25 */
    27,27,
    /* say_0707, 2 bytes at 27 */
    7,7,
    /* say_07, 1 bytes at 29 */
    7,
    /* lts_rr, 2 bytes at 30 */
    24,24,
    /* say_16, 1 bytes at 32 */
    22,
    /* say_15, 1 bytes at 33 */
    21,
    /* say_0d, 1 bytes at 34 */
    13,
    /* say_05, 1 bytes at 35 */
    5,
    /* say_050a, 2 bytes at 36 */
    5,10,
    /* say_1e, 1 bytes at 38 */
    30,
    /* lts_ll, 2 bytes at 39 */
    19,19,
    /* say_1717, 2 bytes at 41 */
    23,23,
    /* say_17, 1 bytes at 43 */
    23,
    /* lts_mm, 2 bytes at 44 */
    20,20,
    /* say_1111, 2 bytes at 46 */
    17,17,
    /* say_11, 1 bytes at 48 */
    17,
    /* lts_nn, 2 bytes at 49 */
    21,21,
    /* say_1212, 2 bytes at 51 */
    18,18,
    /* lts_ce, 2 bytes at 53 */
    12,2,
    /* say_12, 1 bytes at 55 */
    18,
    /* lts_ci, 2 bytes at 56 */
    12,3,
    /* lts_ge, 2 bytes at 58 */
    15,2,
    /* lts_gi, 2 bytes at 60 */
    15,3,
    /* lts_c, 1 bytes at 62 */
    12,
    /* say_14, 1 bytes at 63 */
    20,
    /* lts_g, 1 bytes at 64 */
    15,
    /* lts_cch, 3 bytes at 65 */
    12,12,16,
    /* say_0505, 2 bytes at 68 */
    5,5,
    /* lts_cc, 2 bytes at 70 */
    12,12,
    /* say_040e, 2 bytes at 72 */
    4,14,
    /* lts_cci, 3 bytes at 74 */
    12,12,3,
    /* lts_62, 1 bytes at 77 */
    98,
    /* lts_6c, 1 bytes at 78 */
    108,
    /* lts_63, 1 bytes at 79 */
    99,
    /* lts_6d, 1 bytes at 80 */
    109,
    /* lts_ch, 2 bytes at 81 */
    12,16,
    /* lts_ck, 2 bytes at 83 */
    12,18,
    /* say_0e, 1 bytes at 85 */
    14,
    /* lts_ss, 2 bytes at 86 */
    25,25,
    /* say_0a0a, 2 bytes at 88 */
    10,10,
    /* lts_sh, 2 bytes at 90 */
    25,16,
    /* lts_sc, 2 bytes at 92 */
    25,12,
    /* lts_sciatica, 8 bytes at 94 */
    25,12,3,1,26,3,12,1,
    /* lts_sciatto, 7 bytes at 102 */
    25,12,3,1,26,26,4,
    /* lts_sci, 3 bytes at 109 */
    25,12,3,
    /* lts_scia, 4 bytes at 112 */
    25,12,3,1,
    /* lts_sciamo, 6 bytes at 116 */
    25,12,3,1,20,4,
    /* lts_sciano, 6 bytes at 122 */
    25,12,3,1,21,4,
    /* lts_sciare, 6 bytes at 128 */
    25,12,3,1,24,2,
    /* lts_scie, 4 bytes at 134 */
    25,12,3,2,
    /* lts_scio, 4 bytes at 138 */
    25,12,3,4,
    /* say_0c1b, 2 bytes at 142 */
    12,27,
    /* lts_sciat, 5 bytes at 144 */
    25,12,3,1,26,
    /* lts_sciav, 5 bytes at 149 */
    25,12,3,1,27,
    /* lts_scier, 5 bytes at 154 */
    25,12,3,2,24,
    /* lts_b, 1 bytes at 159 */
    11,
    /* say_09, 1 bytes at 160 */
    9,
    /* lts_l, 1 bytes at 161 */
    19,
    /* lts_r, 1 bytes at 162 */
    24,
    /* lts_v, 1 bytes at 163 */
    27,
    /* lts_aseps, 5 bytes at 164 */
    1,25,2,22,25,
    /* lts_asim, 4 bytes at 169 */
    1,25,3,20,
    /* lts_casori, 6 bytes at 173 */
    12,1,25,4,24,3,
    /* lts_dinosaur, 8 bytes at 179 */
    13,3,21,4,25,1,5,24,
    /* lts_girasol, 7 bytes at 187 */
    15,3,24,1,25,4,19,
    /* lts_rosic, 5 bytes at 194 */
    24,4,25,3,12,
    /* lts_staser, 6 bytes at 199 */
    25,26,1,25,2,24,
    /* say_0a, 1 bytes at 205 */
    10,
};

const delta_store itit_delta_authored_store[] = {
    { itit_evv_authored_data, sizeof itit_evv_authored_data },
    { 0, 0 },
};
