/* Generated by tools/rules/consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/itit/rules/constants.
   The lifted ones are in delta_consts_itit.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t itit_evv_authored_data[] = {
    /* fence_03, 1 bytes at 0 */
    3,
    /* lts_bb, 2 bytes at 1 */
    11,11,
    /* say_0101, 2 bytes at 3 */
    1,1,
    /* say_01, 1 bytes at 5 */
    1,
    /* lts_dd, 2 bytes at 6 */
    13,13,
    /* say_0303, 2 bytes at 8 */
    3,3,
    /* lts_ff, 2 bytes at 10 */
    14,14,
    /* say_0808, 2 bytes at 12 */
    8,8,
    /* say_08, 1 bytes at 14 */
    8,
    /* lts_pp, 2 bytes at 15 */
    22,22,
    /* say_0202, 2 bytes at 17 */
    2,2,
    /* say_02, 1 bytes at 19 */
    2,
    /* lts_tt, 2 bytes at 20 */
    26,26,
    /* say_0404, 2 bytes at 22 */
    4,4,
    /* say_04, 1 bytes at 24 */
    4,
    /* lts_vv, 2 bytes at 25 */
    27,27,
    /* say_0707, 2 bytes at 27 */
    7,7,
    /* say_07, 1 bytes at 29 */
    7,
    /* lts_rr, 2 bytes at 30 */
    24,24,
    /* say_16, 1 bytes at 32 */
    22,
    /* say_15, 1 bytes at 33 */
    21,
    /* say_0d, 1 bytes at 34 */
    13,
    /* say_05, 1 bytes at 35 */
    5,
    /* say_050a, 2 bytes at 36 */
    5,10,
    /* say_1e, 1 bytes at 38 */
    30,
    /* lts_ll, 2 bytes at 39 */
    19,19,
    /* say_1717, 2 bytes at 41 */
    23,23,
    /* say_17, 1 bytes at 43 */
    23,
    /* lts_mm, 2 bytes at 44 */
    20,20,
    /* say_1111, 2 bytes at 46 */
    17,17,
    /* say_11, 1 bytes at 48 */
    17,
    /* lts_nn, 2 bytes at 49 */
    21,21,
    /* say_1212, 2 bytes at 51 */
    18,18,
    /* lts_ce, 2 bytes at 53 */
    12,2,
    /* say_12, 1 bytes at 55 */
    18,
    /* lts_ci, 2 bytes at 56 */
    12,3,
    /* lts_ge, 2 bytes at 58 */
    15,2,
    /* lts_gi, 2 bytes at 60 */
    15,3,
    /* lts_c, 1 bytes at 62 */
    12,
    /* say_14, 1 bytes at 63 */
    20,
    /* lts_g, 1 bytes at 64 */
    15,
    /* lts_cch, 3 bytes at 65 */
    12,12,16,
    /* say_0505, 2 bytes at 68 */
    5,5,
    /* lts_cc, 2 bytes at 70 */
    12,12,
    /* say_040e, 2 bytes at 72 */
    4,14,
    /* lts_cci, 3 bytes at 74 */
    12,12,3,
    /* lts_62, 1 bytes at 77 */
    98,
    /* lts_6c, 1 bytes at 78 */
    108,
    /* lts_63, 1 bytes at 79 */
    99,
    /* lts_6d, 1 bytes at 80 */
    109,
    /* lts_ch, 2 bytes at 81 */
    12,16,
    /* lts_ck, 2 bytes at 83 */
    12,18,
    /* say_0e, 1 bytes at 85 */
    14,
};

const delta_store itit_delta_authored_store[] = {
    { itit_evv_authored_data, sizeof itit_evv_authored_data },
    { 0, 0 },
};
