/* Generated by tools/module/gather.py. Do not edit.

   esmx as one table, which is the only name the engine knows it by.
   Everything below is defined by one of the generated files beside this,
   under a name carrying the language, because a program may have several
   languages in it and IBM gave the tables the same names in every module.
   src/delta/delta_lang.h says how the engine reaches whichever is in force. */

#include "delta.h"
#include "delta_rules_c.h"
#include "delta_rules_esmx.h"

extern const int32_t esmx_eci_library_lang;
extern const char    esmx_eci_library_name[];
extern const char    esmx_eciIni[];
extern const int32_t esmx_eciIniSize;
extern const int32_t esmx_delta_state_bytes;

extern const int8_t              esmx_delta_globals[];
extern const int32_t             esmx_delta_globals_n;
extern const delta_compound_decl esmx_delta_compounds[];

extern delta_stmt esmx_vstmtbl[];
extern void       esmx_viasizes(void);

extern void esmx_link_new(delta_state *d);
extern void esmx_link_delete(delta_state *d);
extern void esmx_set_dict_new(delta_state *d);
extern void esmx_set_dict_delete(delta_state *d);
extern void esmx_act_dict_new(delta_state *d);
extern void esmx_act_dict_delete(delta_state *d);

extern const delta_rule_c *const esmx_delta_rule_native[];

extern const delta_store esmx_delta_authored_store[];

extern const delta_codepoint esmx_delta_codepoints[];
extern const int32_t esmx_delta_codepoints_n;

/* The two slots the runtime fills in for this language: the symbol table,
   once delta_syms_bind has copied the stores into the arena, and the index
   of whichever rules are written as C. Not const, unlike everything else
   here, which is why the language holds their addresses. */
const int32_t *esmx_delta_sym_ref;
delta_rule_cfn *esmx_delta_native_index;

/* The five entries the engine drives a machine through are rules, so the
   shim declares each taking the machine as a value, the way every rule
   does. The engine holds a pointer, so each gets a wrapper of the shape it
   holds them in rather than a cast that would be a lie on a host where a
   pointer is wider than a value. */
extern int32_t esmx_DeltaProc_start(int32_t d);
extern int32_t esmx_DeltaProc_end(int32_t d);
extern int32_t esmx_DeltaProc_flush(int32_t d);
extern int32_t esmx_DeltaProc_process_sentences(int32_t d);
extern int32_t esmx_DeltaProc_process_remaining(int32_t d);
extern int32_t esmx_DeltaProc_main(int32_t d);

static int32_t proc_start(delta_state *d)
{
    return esmx_DeltaProc_start(EVV_REF(d));
}

static int32_t proc_end(delta_state *d)
{
    return esmx_DeltaProc_end(EVV_REF(d));
}

static int32_t proc_flush(delta_state *d)
{
    return esmx_DeltaProc_flush(EVV_REF(d));
}

static int32_t proc_process_sentences(delta_state *d)
{
    return esmx_DeltaProc_process_sentences(EVV_REF(d));
}

static int32_t proc_process_remaining(delta_state *d)
{
    return esmx_DeltaProc_process_remaining(EVV_REF(d));
}

static int32_t proc_main(delta_state *d)
{
    return esmx_DeltaProc_main(EVV_REF(d));
}


/* Not const, because the numbers below cannot go in an initialiser: each
   lives in another file as a const object, which C does not count as a
   constant expression. delta_lang_bind_esmx fills them in once, before
   anything asks the language anything. */
delta_language delta_lang_esmx = {
    "esmx",
    "Mexican Spanish",
    0, 0, 0,             /* id, library name, how big a machine is */

    /* The bytecode, the constants it names and the tables it jumps
       through. Nothing but the interpreter ever reads them, so a build with
       every rule written as C says nought here rather than naming them --
       which is what lets the linker drop the megabyte and a half they come
       to. The rule table below stays: it carries the names and the shapes,
       which both forms want. */
#ifdef EVV_NO_BYTECODE
    0, 0, 0,
#else
    esmx_delta_rule_code,
    esmx_delta_rule_imm,
    esmx_delta_rule_map,
#endif
    esmx_delta_rule_entry,
    esmx_delta_rule_argmask,
    esmx_delta_rule_entry_name,
    esmx_delta_rule_sym,
    0,                   /* how many of those */
    esmx_delta_rules,
    0, 0,                /* how many, and which one plants a landing place */
    DELTA_RULE_FRAME_MAX,
    esmx_delta_rule_native,
    &esmx_delta_native_index,

    esmx_delta_const_store,
    esmx_delta_authored_store,
    esmx_delta_codepoints,
    0,                   /* how many of those */
    &esmx_delta_sym_ref,

    esmx_vstmtbl,
    esmx_viasizes,

    esmx_delta_globals,
    0,                   /* how many */
    esmx_delta_compounds,

    esmx_link_new,
    esmx_link_delete,
    esmx_set_dict_new,
    esmx_set_dict_delete,
    esmx_act_dict_new,
    esmx_act_dict_delete,

    proc_start,
    proc_end,
    proc_flush,
    proc_process_sentences,
    proc_process_remaining,
    proc_main,

    0, 0,                /* the settings blob and its size */
};

void delta_lang_bind_esmx(void)
{
    delta_language *l = &delta_lang_esmx;

    l->id             = esmx_eci_library_lang;
    l->library_name   = esmx_eci_library_name;
    l->state_bytes    = esmx_delta_state_bytes;
    l->rule_sym_count = esmx_delta_rule_sym_count;
    l->rule_count     = esmx_delta_rule_count;
    l->rule_setjmp    = esmx_delta_rule_setjmp;
    l->globals_n      = esmx_delta_globals_n;
    l->codepoints_n   = esmx_delta_codepoints_n;
    l->ini            = esmx_eciIni;
    l->ini_size       = esmx_eciIniSize;
}
