/* Generated by tools/rules/consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/enus/rules/constants.
   The lifted ones are in delta_consts_enus.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t enus_evv_authored_data[] = {
    /* lex_prefix_re, 2 bytes at 0 */
    24,2,
    /* eti_null, 1 bytes at 2 */
    0,
    /* eti_s_1b90d7, 1 bytes at 3 */
    72,
    /* eti_s_1b90d8, 1 bytes at 4 */
    71,
    /* eti_s_1b90d9, 1 bytes at 5 */
    81,
    /* eti_s_1b90da, 1 bytes at 6 */
    96,
    /* eti_s_1b90db, 1 bytes at 7 */
    73,
    /* eti_s_1b90dc, 1 bytes at 8 */
    168,
    /* eti_s_1b90dd, 1 bytes at 9 */
    172,
    /* eti_s_1b90de, 1 bytes at 10 */
    65,
    /* eti_s_1b90df, 1 bytes at 11 */
    79,
    /* eti_s_1b90e0, 2 bytes at 12 */
    199,72,
    /* eti_s_1b90e2, 3 bytes at 14 */
    199,64,72,
    /* eti_s_1b90e5, 2 bytes at 17 */
    16,26,
    /* eti_s_1b90e7, 1 bytes at 19 */
    14,
    /* eti_s_1b90e8, 2 bytes at 20 */
    26,22,
    /* eti_s_1b90ea, 3 bytes at 22 */
    67,88,88,
    /* eti_s_1b90ed, 4 bytes at 25 */
    28,28,28,65,
    /* eti_s_1b90f1, 5 bytes at 29 */
    72,65,65,65,72,
    /* eti_s_1b90f6, 1 bytes at 34 */
    88,
    /* eti_s_1b90f7, 5 bytes at 35 */
    199,72,76,53,72,
    /* eti_s_1b90fc, 1 bytes at 40 */
    93,
    /* eti_s_1b90fd, 1 bytes at 41 */
    67,
    /* eti_s_1b90fe, 1 bytes at 42 */
    63,
    /* eti_s_1b90ff, 1 bytes at 43 */
    66,
    /* eti_s_1b9100, 1 bytes at 44 */
    69,
    /* eti_s_1b9101, 1 bytes at 45 */
    68,
    /* eti_s_1b9102, 1 bytes at 46 */
    64,
    /* eti_s_1b9103, 1 bytes at 47 */
    4,
    /* eti_s_1b9104, 1 bytes at 48 */
    70,
    /* eti_s_1b9105, 2 bytes at 49 */
    70,71,
    /* eti_s_1b9112, 6 bytes at 51 */
    199,72,76,54,72,72,
    /* eti_s_1b9118, 1 bytes at 57 */
    167,
    /* eti_s_1b9119, 1 bytes at 58 */
    76,
    /* eti_s_1b911a, 1 bytes at 59 */
    171,
    /* eti_s_1b911d, 1 bytes at 60 */
    80,
    /* eti_s_1b911e, 1 bytes at 61 */
    83,
    /* eti_s_1b911f, 1 bytes at 62 */
    82,
    /* eti_s_1b9120, 1 bytes at 63 */
    94,
    /* eti_s_1b9121, 1 bytes at 64 */
    95,
    /* eti_s_1b9126, 1 bytes at 65 */
    78,
    /* eti_s_1b9127, 9 bytes at 66 */
    72,76,53,72,72,13,4,26,72,
    /* eti_s_1b9130, 4 bytes at 75 */
    25,26,1,24,
    /* eti_s_1b9134, 1 bytes at 79 */
    25,
    /* eti_s_1b9135, 1 bytes at 80 */
    46,
    /* eti_s_1b9136, 2 bytes at 81 */
    72,72,
    /* eti_s_1b9138, 1 bytes at 83 */
    84,
    /* eti_s_1b9139, 2 bytes at 84 */
    65,72,
    /* eti_s_1b913b, 1 bytes at 86 */
    199,
    /* fence_03, 1 bytes at 87 */
    3,
    /* lts_bt, 2 bytes at 88 */
    11,26,
    /* say_04, 1 bytes at 90 */
    4,
    /* say_01, 1 bytes at 91 */
    1,
    /* lts_wr, 2 bytes at 92 */
    28,24,
    /* say_18, 1 bytes at 94 */
    24,
    /* say_1b, 1 bytes at 95 */
    27,
    /* lts_dg, 2 bytes at 96 */
    13,15,
    /* say_11, 1 bytes at 98 */
    17,
    /* lts_dj, 2 bytes at 99 */
    13,17,
    /* lts_mech, 4 bytes at 101 */
    20,2,12,16,
    /* say_141f07, 3 bytes at 105 */
    20,31,7,
    /* lts_mn, 2 bytes at 108 */
    20,21,
    /* say_15, 1 bytes at 110 */
    21,
    /* say_14, 1 bytes at 111 */
    20,
    /* lts_mb, 2 bytes at 112 */
    20,11,
    /* lts_ng, 2 bytes at 114 */
    21,15,
    /* say_16, 1 bytes at 116 */
    22,
    /* lts_then, 4 bytes at 117 */
    26,16,2,21,
    /* lts_ton, 3 bytes at 121 */
    26,4,21,
    /* lts_qu, 2 bytes at 124 */
    23,5,
    /* lts_et, 2 bytes at 126 */
    2,26,
    /* say_07, 1 bytes at 128 */
    7,
    /* lts_e, 1 bytes at 129 */
    2,
    /* say_071b, 2 bytes at 130 */
    7,27,
};

const delta_store enus_delta_authored_store[] = {
    { enus_evv_authored_data, sizeof enus_evv_authored_data },
    { 0, 0 },
};
