/* Generated by tools/rules/consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/enus/rules/constants.
   The lifted ones are in delta_consts_enus.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t enus_evv_authored_data[] = {
    /* lex_prefix_re, 2 bytes at 0 */
    24,2,
    /* eng_open_paren, 1 bytes at 2 */
    70,
    /* eng_paren_s, 3 bytes at 3 */
    70,25,71,
    /* eng_paren_es, 4 bytes at 6 */
    70,2,25,71,
    /* eng_paren_ed, 4 bytes at 10 */
    70,2,13,71,
    /* eng_open_bracket, 1 bytes at 14 */
    80,
    /* eng_open_brace, 1 bytes at 15 */
    82,
    /* eng_number_sign, 1 bytes at 16 */
    74,
    /* eng_dollar, 1 bytes at 17 */
    85,
    /* eng_asterisk, 1 bytes at 18 */
    78,
    /* eng_tilde, 1 bytes at 19 */
    77,
    /* eng_space, 2 bytes at 20 */
    199,72,
    /* eti_null, 1 bytes at 22 */
    0,
    /* eti_s_1b90d7, 1 bytes at 23 */
    72,
    /* eti_s_1b90d8, 1 bytes at 24 */
    71,
    /* eti_s_1b90d9, 1 bytes at 25 */
    81,
    /* eti_s_1b90da, 1 bytes at 26 */
    96,
    /* eti_s_1b90db, 1 bytes at 27 */
    73,
    /* eti_s_1b90dc, 1 bytes at 28 */
    168,
    /* eti_s_1b90dd, 1 bytes at 29 */
    172,
    /* eti_s_1b90de, 1 bytes at 30 */
    65,
    /* eti_s_1b90fd, 1 bytes at 31 */
    67,
    /* eti_s_1b90ff, 1 bytes at 32 */
    66,
    /* eti_s_1b9100, 1 bytes at 33 */
    69,
    /* eti_s_1b9101, 1 bytes at 34 */
    68,
    /* eti_s_1b9102, 1 bytes at 35 */
    64,
    /* eti_s_1b9103, 1 bytes at 36 */
    4,
    /* eti_s_1b9104, 1 bytes at 37 */
    70,
    /* eti_s_1b9105, 2 bytes at 38 */
    70,71,
    /* eti_s_1b9118, 1 bytes at 40 */
    167,
    /* eti_s_1b9119, 1 bytes at 41 */
    76,
    /* eti_s_1b911a, 1 bytes at 42 */
    171,
    /* eti_s_1b911d, 1 bytes at 43 */
    80,
    /* eti_s_1b911e, 1 bytes at 44 */
    83,
    /* eti_s_1b911f, 1 bytes at 45 */
    82,
    /* eti_s_1b9120, 1 bytes at 46 */
    94,
    /* eti_s_1b9121, 1 bytes at 47 */
    95,
    /* eti_s_1b9134, 1 bytes at 48 */
    25,
    /* eti_s_1b9135, 1 bytes at 49 */
    46,
    /* eti_s_1b9136, 2 bytes at 50 */
    72,72,
    /* eti_s_1b9138, 1 bytes at 52 */
    84,
    /* eti_s_1b9139, 2 bytes at 53 */
    65,72,
    /* eti_s_1b913b, 1 bytes at 55 */
    199,
    /* fence_03, 1 bytes at 56 */
    3,
    /* lts_bt, 2 bytes at 57 */
    11,26,
    /* say_04, 1 bytes at 59 */
    4,
    /* say_01, 1 bytes at 60 */
    1,
    /* lts_wr, 2 bytes at 61 */
    28,24,
    /* say_18, 1 bytes at 63 */
    24,
    /* say_1b, 1 bytes at 64 */
    27,
    /* lts_dg, 2 bytes at 65 */
    13,15,
    /* say_11, 1 bytes at 67 */
    17,
    /* lts_dj, 2 bytes at 68 */
    13,17,
    /* lts_mech, 4 bytes at 70 */
    20,2,12,16,
    /* say_141f07, 3 bytes at 74 */
    20,31,7,
    /* lts_mn, 2 bytes at 77 */
    20,21,
    /* say_15, 1 bytes at 79 */
    21,
    /* say_14, 1 bytes at 80 */
    20,
    /* lts_mb, 2 bytes at 81 */
    20,11,
    /* lts_ng, 2 bytes at 83 */
    21,15,
    /* say_16, 1 bytes at 85 */
    22,
    /* lts_then, 4 bytes at 86 */
    26,16,2,21,
    /* lts_ton, 3 bytes at 90 */
    26,4,21,
    /* lts_qu, 2 bytes at 93 */
    23,5,
    /* lts_et, 2 bytes at 95 */
    2,26,
    /* say_07, 1 bytes at 97 */
    7,
    /* lts_e, 1 bytes at 98 */
    2,
    /* say_071b, 2 bytes at 99 */
    7,27,
};

const delta_store enus_delta_authored_store[] = {
    { enus_evv_authored_data, sizeof enus_evv_authored_data },
    { 0, 0 },
};
