/* Generated by tools/rules/consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/eses/rules/constants.
   The lifted ones are in delta_consts_eses.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t eses_evv_authored_data[] = {
    /* fence_03, 1 bytes at 0 */
    3,
    /* say_04, 1 bytes at 1 */
    4,
    /* say_05, 1 bytes at 2 */
    5,
    /* say_0b, 1 bytes at 3 */
    11,
    /* say_10, 1 bytes at 4 */
    16,
    /* say_16, 1 bytes at 5 */
    22,
    /* say_18, 1 bytes at 6 */
    24,
    /* say_1e, 1 bytes at 7 */
    30,
    /* say_0f, 1 bytes at 8 */
    15,
    /* say_0d, 1 bytes at 9 */
    13,
    /* lts_ll, 2 bytes at 10 */
    19,19,
    /* say_15, 1 bytes at 12 */
    21,
    /* say_1c, 1 bytes at 13 */
    28,
    /* lts_qu, 2 bytes at 14 */
    23,5,
    /* lts_e, 1 bytes at 16 */
    2,
    /* lts_6c, 1 bytes at 17 */
    108,
    /* lts_6d, 1 bytes at 18 */
    109,
    /* say_0e, 1 bytes at 19 */
    14,
    /* lts_l, 1 bytes at 20 */
    19,
    /* lts_m, 1 bytes at 21 */
    20,
};

const delta_store eses_delta_authored_store[] = {
    { eses_evv_authored_data, sizeof eses_evv_authored_data },
    { 0, 0 },
};
