/* Generated by tools/rules/consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/eses/rules/constants.
   The lifted ones are in delta_consts_eses.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t eses_evv_authored_data[] = {
    /* fence_03, 1 bytes at 0 */
    3,
    /* say_04, 1 bytes at 1 */
    4,
    /* say_05, 1 bytes at 2 */
    5,
    /* say_0b, 1 bytes at 3 */
    11,
    /* say_10, 1 bytes at 4 */
    16,
    /* say_16, 1 bytes at 5 */
    22,
    /* say_18, 1 bytes at 6 */
    24,
    /* say_1e, 1 bytes at 7 */
    30,
};

const delta_store eses_delta_authored_store[] = {
    { eses_evv_authored_data, sizeof eses_evv_authored_data },
    { 0, 0 },
};
