/* Generated by tools/delta-consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/plpl/rules/constants.
   The lifted ones are in delta_consts_plpl.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t plpl_evv_authored_data[] = {
    /* pol_letter_aogonek, 1 bytes at 0 */
    207,
    /* pol_letter_cacute, 1 bytes at 1 */
    208,
    /* pol_letter_eogonek, 1 bytes at 2 */
    209,
    /* pol_letter_lstroke, 1 bytes at 3 */
    210,
    /* pol_letter_nacute, 1 bytes at 4 */
    211,
    /* pol_letter_sacute, 1 bytes at 5 */
    212,
    /* pol_letter_zacute, 1 bytes at 6 */
    213,
    /* pol_letter_zdot, 1 bytes at 7 */
    214,
    /* pol_ph_on, 2 bytes at 8 */
    33,18,
    /* pol_ph_en, 2 bytes at 10 */
    29,18,
    /* pol_ph_tsz, 2 bytes at 12 */
    4,24,
    /* pol_ph_dzz, 2 bytes at 14 */
    3,22,
    /* pol_name_cacute, 3 bytes at 16 */
    12,3,2,
    /* pol_name_lstroke, 2 bytes at 19 */
    2,210,
    /* pol_name_nacute, 2 bytes at 21 */
    2,211,
    /* pol_name_sacute, 2 bytes at 23 */
    2,212,
    /* pol_name_zacute, 4 bytes at 25 */
    31,3,2,26,
    /* pol_name_zdot, 3 bytes at 29 */
    214,2,26,
};

const delta_store plpl_delta_authored_store[] = {
    { plpl_evv_authored_data, sizeof plpl_evv_authored_data },
    { 0, 0 },
};
