/* Generated by tools/rules/consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/plpl/rules/constants.
   The lifted ones are in delta_consts_plpl.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t plpl_evv_authored_data[] = {
    /* pol_letter_aogonek, 1 bytes at 0 */
    207,
    /* pol_letter_cacute, 1 bytes at 1 */
    208,
    /* pol_letter_eogonek, 1 bytes at 2 */
    209,
    /* pol_letter_lstroke, 1 bytes at 3 */
    210,
    /* pol_letter_nacute, 1 bytes at 4 */
    211,
    /* pol_letter_sacute, 1 bytes at 5 */
    212,
    /* pol_letter_zacute, 1 bytes at 6 */
    213,
    /* pol_letter_zdot, 1 bytes at 7 */
    214,
    /* pol_ph_on, 2 bytes at 8 */
    33,18,
    /* pol_ph_en, 2 bytes at 10 */
    29,18,
    /* pol_ph_tsz, 2 bytes at 12 */
    4,24,
    /* pol_ph_dzz, 2 bytes at 14 */
    3,22,
    /* pol_name_cacute, 3 bytes at 16 */
    12,3,2,
    /* pol_name_lstroke, 2 bytes at 19 */
    2,210,
    /* pol_name_nacute, 2 bytes at 21 */
    2,211,
    /* pol_name_sacute, 2 bytes at 23 */
    2,212,
    /* pol_name_zacute, 4 bytes at 25 */
    31,3,2,26,
    /* pol_name_zdot, 3 bytes at 29 */
    214,2,26,
    /* pol_name_a, 1 bytes at 32 */
    1,
    /* pol_name_b, 2 bytes at 33 */
    11,2,
    /* pol_name_c, 2 bytes at 35 */
    12,2,
    /* pol_name_d, 2 bytes at 37 */
    13,2,
    /* pol_name_e, 1 bytes at 39 */
    2,
    /* pol_name_f, 2 bytes at 40 */
    2,14,
    /* pol_name_g, 3 bytes at 42 */
    15,3,2,
    /* pol_name_h, 2 bytes at 45 */
    16,1,
    /* pol_name_i, 1 bytes at 47 */
    3,
    /* pol_name_j, 3 bytes at 48 */
    17,4,26,
    /* pol_name_k, 2 bytes at 51 */
    18,1,
    /* pol_name_l, 2 bytes at 53 */
    2,19,
    /* pol_name_m, 2 bytes at 55 */
    2,20,
    /* pol_name_n, 2 bytes at 57 */
    2,21,
    /* pol_name_o, 1 bytes at 59 */
    4,
    /* pol_name_p, 2 bytes at 60 */
    22,2,
    /* pol_name_q, 2 bytes at 62 */
    18,5,
    /* pol_name_r, 2 bytes at 64 */
    2,24,
    /* pol_name_s, 2 bytes at 66 */
    2,25,
    /* pol_name_t, 2 bytes at 68 */
    26,2,
    /* pol_name_u, 1 bytes at 70 */
    5,
    /* pol_name_v, 3 bytes at 71 */
    14,1,28,
    /* pol_name_w, 2 bytes at 74 */
    28,5,
    /* pol_name_x, 3 bytes at 76 */
    3,18,25,
    /* pol_name_y, 5 bytes at 79 */
    3,15,24,2,18,
    /* pol_name_z, 3 bytes at 84 */
    31,2,26,
    /* pol_num_2, 3 bytes at 87 */
    13,28,1,
    /* pol_num_3, 4 bytes at 90 */
    26,24,31,30,
    /* pol_num_4, 6 bytes at 94 */
    12,31,26,2,24,30,
    /* pol_num_5, 4 bytes at 100 */
    22,3,209,208,
    /* pol_num_6, 5 bytes at 104 */
    25,31,2,212,208,
    /* pol_num_7, 6 bytes at 109 */
    25,3,2,13,2,20,
    /* pol_num_8, 5 bytes at 115 */
    4,25,3,2,20,
    /* pol_num_9, 8 bytes at 120 */
    13,31,3,2,28,3,209,208,
    /* pol_num_10, 8 bytes at 128 */
    13,31,3,2,25,3,209,208,
    /* pol_num_11, 10 bytes at 136 */
    17,2,13,2,21,1,212,12,3,2,
    /* pol_num_12, 9 bytes at 146 */
    13,28,1,21,1,212,12,3,2,
    /* pol_num_13, 10 bytes at 155 */
    26,24,31,30,21,1,212,12,3,2,
    /* pol_num_14, 11 bytes at 165 */
    12,31,26,2,24,21,1,212,12,3,2,
    /* pol_num_15, 10 bytes at 176 */
    22,3,209,26,21,1,212,12,3,2,
    /* pol_num_16, 10 bytes at 186 */
    25,31,2,25,21,1,212,12,3,2,
    /* pol_num_17, 12 bytes at 196 */
    25,3,2,13,2,20,21,1,212,12,3,2,
    /* pol_num_18, 11 bytes at 208 */
    4,25,3,2,20,21,1,212,12,3,2,
    /* pol_num_19, 14 bytes at 219 */
    13,31,3,2,28,3,209,26,21,1,212,12,3,2,
    /* pol_num_20, 12 bytes at 233 */
    13,28,1,13,31,3,2,212,12,3,1,72,
    /* pol_num_30, 12 bytes at 245 */
    26,24,31,30,13,31,3,2,212,12,3,72,
    /* pol_num_40, 13 bytes at 257 */
    12,31,26,2,24,13,31,3,2,212,12,3,72,
    /* pol_num_50, 13 bytes at 270 */
    22,3,209,208,13,31,3,2,25,3,207,26,72,
    /* pol_num_60, 14 bytes at 283 */
    25,31,2,212,208,13,31,3,2,25,3,207,26,72,
    /* pol_num_70, 15 bytes at 297 */
    25,3,2,13,2,20,13,31,3,2,25,3,207,26,72,
    /* pol_num_80, 14 bytes at 312 */
    4,25,3,2,20,13,31,3,2,25,3,207,26,72,
    /* pol_num_90, 17 bytes at 326 */
    13,31,3,2,28,3,209,208,13,31,3,2,25,3,207,26,
    72,
    /* pol_num_1, 5 bytes at 343 */
    17,2,13,2,21,
    /* pol_num_100, 3 bytes at 348 */
    25,26,4,
    /* pol_num_100j, 4 bytes at 351 */
    199,25,2,26,
    /* pol_num_1000, 6 bytes at 355 */
    26,30,25,3,207,12,
    /* pol_num_1000j, 9 bytes at 361 */
    199,72,26,30,25,3,207,12,2,
    /* pol_num_mln, 8 bytes at 370 */
    199,72,20,3,19,3,4,21,
    /* pol_num_mlns, 9 bytes at 378 */
    199,72,20,3,19,3,4,21,30,
    /* pol_num_mld, 9 bytes at 387 */
    199,72,20,3,19,3,1,24,13,
    /* pol_num_mlds, 10 bytes at 396 */
    199,72,20,3,19,3,1,24,13,30,
    /* pol_num_and, 2 bytes at 406 */
    199,72,
    /* pol_ph_aogonek, 1 bytes at 408 */
    35,
    /* pol_letter_p, 1 bytes at 409 */
    22,
    /* pol_letter_t, 1 bytes at 410 */
    26,
    /* pol_letter_k, 1 bytes at 411 */
    18,
    /* pol_letter_f, 1 bytes at 412 */
    14,
    /* pol_letter_s, 1 bytes at 413 */
    25,
    /* pol_letter_c, 1 bytes at 414 */
    12,
    /* pol_letter_h, 1 bytes at 415 */
    16,
    /* pol_ph_x, 1 bytes at 416 */
    36,
    /* pol_letter_w, 1 bytes at 417 */
    28,
    /* pol_letter_z, 1 bytes at 418 */
    31,
    /* pol_capital_w, 1 bytes at 419 */
    49,
    /* pol_capital_z, 1 bytes at 420 */
    52,
    /* pol_letter_e, 1 bytes at 421 */
    2,
    /* pol_fw_na, 2 bytes at 422 */
    21,1,
    /* pol_fw_do, 2 bytes at 424 */
    13,4,
    /* pol_fw_po, 2 bytes at 426 */
    22,4,
    /* pol_fw_od, 2 bytes at 428 */
    4,13,
    /* pol_fw_za, 2 bytes at 430 */
    31,1,
    /* pol_fw_o, 1 bytes at 432 */
    4,
    /* pol_fw_u, 1 bytes at 433 */
    5,
    /* pol_fw_ku, 2 bytes at 434 */
    18,5,
    /* pol_fw_ze, 2 bytes at 436 */
    31,2,
    /* pol_fw_we, 2 bytes at 438 */
    28,2,
    /* pol_fw_przy, 4 bytes at 440 */
    22,24,31,30,
    /* pol_fw_bez, 3 bytes at 444 */
    11,2,31,
    /* pol_fw_dla, 3 bytes at 447 */
    13,19,1,
    /* pol_fw_przez, 5 bytes at 450 */
    22,24,31,2,31,
    /* pol_fw_pod, 3 bytes at 455 */
    22,4,13,
    /* pol_fw_nad, 3 bytes at 458 */
    21,1,13,
    /* pol_fw_przed, 5 bytes at 461 */
    22,24,31,2,13,
    /* pol_fw_znad, 4 bytes at 466 */
    31,21,1,13,
    /* pol_fw_spod, 4 bytes at 470 */
    25,22,4,13,
    /* pol_fw_zza, 3 bytes at 474 */
    31,31,1,
    /* pol_fw_sprzed, 6 bytes at 477 */
    25,22,24,31,2,13,
    /* pol_fw_i, 1 bytes at 483 */
    3,
    /* pol_fw_a, 1 bytes at 484 */
    1,
    /* pol_fw_sie_, 3 bytes at 485 */
    25,3,209,
    /* pol_fw_z_e, 2 bytes at 488 */
    214,2,
    /* pol_fw_nie, 3 bytes at 490 */
    21,3,2,
    /* pol_capital_nie, 3 bytes at 493 */
    42,3,2,
    /* pol_ph_t, 1 bytes at 496 */
    4,
    /* pol_ph_d, 1 bytes at 497 */
    3,
    /* pol_ph_sz, 1 bytes at 498 */
    24,
    /* pol_ph_zh, 1 bytes at 499 */
    22,
    /* pol_fence_word, 1 bytes at 500 */
    4,
    /* lts_b, 1 bytes at 501 */
    11,
    /* lts_d, 1 bytes at 502 */
    13,
    /* lts_g, 1 bytes at 503 */
    15,
    /* lts_z, 1 bytes at 504 */
    31,
    /* lts_d5, 1 bytes at 505 */
    213,
    /* lts_d6, 1 bytes at 506 */
    214,
    /* fence_03, 1 bytes at 507 */
    3,
    /* lts_p, 1 bytes at 508 */
    22,
    /* lts_t, 1 bytes at 509 */
    26,
    /* lts_k, 1 bytes at 510 */
    18,
    /* lts_f, 1 bytes at 511 */
    14,
    /* lts_s, 1 bytes at 512 */
    25,
    /* lts_c, 1 bytes at 513 */
    12,
    /* lts_h, 1 bytes at 514 */
    16,
    /* lts_d4, 1 bytes at 515 */
    212,
    /* lts_d0, 1 bytes at 516 */
    208,
    /* lts_sz, 2 bytes at 517 */
    25,31,
    /* lts_cz, 2 bytes at 519 */
    12,31,
    /* lts_szcz, 4 bytes at 521 */
    25,31,12,31,
    /* say_160316, 3 bytes at 525 */
    22,3,22,
    /* say_18, 1 bytes at 528 */
    24,
    /* lts_si, 2 bytes at 529 */
    25,3,
    /* lts_st, 2 bytes at 531 */
    25,26,
    /* say_0903, 2 bytes at 533 */
    9,3,
    /* say_09, 1 bytes at 535 */
    9,
    /* say_0a, 1 bytes at 536 */
    10,
    /* say_0316, 2 bytes at 537 */
    3,22,
    /* say_0418, 2 bytes at 539 */
    4,24,
    /* lts_ch, 2 bytes at 541 */
    12,16,
    /* say_24, 1 bytes at 543 */
    36,
    /* lts_ci, 2 bytes at 544 */
    12,3,
    /* lts_sz_2, 2 bytes at 546 */
    31,25,
    /* lts_cz_2, 2 bytes at 548 */
    31,12,
    /* lts_rz, 2 bytes at 550 */
    24,31,
    /* say_15, 1 bytes at 552 */
    21,
    /* lts_dzi, 3 bytes at 553 */
    13,31,3,
    /* lts_dz, 2 bytes at 556 */
    13,31,
    /* lts_0dd6, 2 bytes at 558 */
    13,214,
    /* lts_0dd5, 2 bytes at 560 */
    13,213,
    /* say_04, 1 bytes at 562 */
    4,
    /* lts_zau, 3 bytes at 563 */
    31,1,5,
    /* say_091e1f, 3 bytes at 566 */
    9,30,31,
    /* lts_zd, 2 bytes at 569 */
    31,13,
    /* say_0a04, 2 bytes at 571 */
    10,4,
    /* lts_zg, 2 bytes at 573 */
    31,15,
    /* say_0a05, 2 bytes at 575 */
    10,5,
    /* lts_zi, 2 bytes at 577 */
    31,3,
    /* say_05, 1 bytes at 579 */
    5,
    /* say_06, 1 bytes at 580 */
    6,
    /* lts_nau, 3 bytes at 581 */
    21,1,5,
    /* say_121e1f, 3 bytes at 584 */
    18,30,31,
    /* lts_nieu, 4 bytes at 587 */
    21,3,2,5,
    /* say_131d1f, 3 bytes at 591 */
    19,29,31,
    /* lts_ni, 2 bytes at 594 */
    21,3,
    /* say_13, 1 bytes at 596 */
    19,
    /* say_1d, 1 bytes at 597 */
    29,
    /* say_21, 1 bytes at 598 */
    33,
    /* say_1c, 1 bytes at 599 */
    28,
    /* say_02, 1 bytes at 600 */
    2,
    /* say_01, 1 bytes at 601 */
    1,
    /* say_08, 1 bytes at 602 */
    8,
    /* say_07, 1 bytes at 603 */
    7,
    /* lts_ff, 2 bytes at 604 */
    14,14,
    /* say_0808, 2 bytes at 606 */
    8,8,
    /* lts_pp, 2 bytes at 608 */
    22,22,
    /* say_0202, 2 bytes at 610 */
    2,2,
    /* lts_tri, 3 bytes at 612 */
    26,24,3,
    /* say_04151b, 3 bytes at 615 */
    4,21,27,
    /* lts_tt, 2 bytes at 618 */
    26,26,
    /* say_0404, 2 bytes at 620 */
    4,4,
    /* lts_vv, 2 bytes at 622 */
    27,27,
    /* say_0707, 2 bytes at 624 */
    7,7,
    /* lts_kt, 2 bytes at 626 */
    18,26,
    /* say_0603, 2 bytes at 628 */
    6,3,
    /* say_050a, 2 bytes at 630 */
    5,10,
    /* say_1e, 1 bytes at 632 */
    30,
    /* lts_ll, 2 bytes at 633 */
    19,19,
    /* say_1717, 2 bytes at 635 */
    23,23,
    /* say_17, 1 bytes at 637 */
    23,
    /* lts_mm, 2 bytes at 638 */
    20,20,
    /* say_1111, 2 bytes at 640 */
    17,17,
    /* say_11, 1 bytes at 642 */
    17,
    /* lts_m, 1 bytes at 643 */
    20,
    /* say_1b, 1 bytes at 644 */
    27,
    /* lts_cf, 1 bytes at 645 */
    207,
    /* lts_d1, 1 bytes at 646 */
    209,
    /* lts_d2, 1 bytes at 647 */
    210,
    /* lts_d3, 1 bytes at 648 */
    211,
    /* say_23, 1 bytes at 649 */
    35,
    /* say_20, 1 bytes at 650 */
    32,
    /* lts_d4d0, 2 bytes at 651 */
    212,208,
    /* say_0b0d, 2 bytes at 653 */
    11,13,
    /* lts_d50dd5, 3 bytes at 655 */
    213,13,213,
    /* say_0c0e, 2 bytes at 658 */
    12,14,
};

const delta_store plpl_delta_authored_store[] = {
    { plpl_evv_authored_data, sizeof plpl_evv_authored_data },
    { 0, 0 },
};
