#!/usr/bin/env python3
"""Bytes a rule of ours names by address.

A rule that tests text names the bytes it tests against by address, and the
address is a symbol: the emitter numbers it, the engine looks it up in the
language's symbol table, and startup has copied the bytes into the arena so
that a thirty-two bit value can name them. All of that already works for the
constants IBM compiled, which come out of its objects with the rules.

This is the same thing for constants there is no object for, which is what
writing a new rule means. The text is one to a line in `lang/<tag>/rules
/constants':

    bytes hello 48 65 6c 6c 6f
    text  stop "stop"

and what it writes is `delta_authored_<tag>.c', the one file in a language
module that no lifter touches, plus the lines in `lang/<tag>/rules/symbols'
that say where each name falls. A rule then says `sym hello' and nothing else
has to know.

The bytes are the bytes. A string a rule holds against the text being read is
not ASCII: it is one code per character in the alphabet the statement type
declares, which tools/delta-lexicon.py prints for a language. `text' is for
the ones that really are ASCII, and `bytes' is for the rest.

usage: delta-consts.py <tag>...     write each language's authored store
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEAD = """/* Generated by tools/delta-consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/%(tag)s/rules/constants.
   The lifted ones are in delta_consts_%(tag)s.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

"""

# What the store is called, and how the symbols file says a name in it belongs
# to no object in particular: a constant of ours is the language's rather than
# one object's, so any rule may name it.
STORE = "%s_evv_authored_data"
ANY = "*"


def read_constants(path):
    """Each constant as a name and its bytes, in the order they are written."""
    out = []
    for n, raw in enumerate(open(path), 1):
        line = raw.split("#")[0].strip()
        if not line:
            continue
        w = line.split(None, 2)
        where = "%s line %d" % (os.path.basename(path), n)
        if len(w) < 3:
            raise ValueError("%s: a constant is a kind, a name and its bytes"
                             % where)
        kind, name, rest = w
        if kind == "bytes":
            try:
                data = bytes(int(b, 16) for b in rest.split())
            except ValueError:
                raise ValueError("%s: %r is not bytes in hex" % (where, rest))
        elif kind == "text":
            if not (rest.startswith('"') and rest.endswith('"')):
                raise ValueError("%s: text goes in quotes" % where)
            data = rest[1:-1].encode("ascii")
        else:
            raise ValueError("%s: no constant called %r" % (where, kind))
        if not data:
            raise ValueError("%s: %s has no bytes" % (where, name))
        out.append((name, data))
    return out


def write_store(tag, out, constants):
    """The bytes as one store, and where each name falls in it."""
    store = STORE % tag
    at = []
    body = []
    off = 0
    for name, data in constants:
        at.append((name, off))
        body.append("    /* %s, %d bytes at %d */"
                    % (name, len(data), off))
        for i in range(0, len(data), 16):
            body.append("    " + ",".join("%d" % b for b in data[i:i + 16])
                        + ",")
        off += len(data)

    with open(out, "w") as f:
        f.write(HEAD % {"tag": tag})
        if constants:
            f.write("uint8_t %s[] = {\n%s\n};\n\n" % (store, "\n".join(body)))
        f.write("const delta_store %s_delta_authored_store[] = {\n" % tag)
        if constants:
            f.write("    { %s, sizeof %s },\n" % (store, store))
        f.write("    { 0, 0 },\n};\n")
    return at


def write_symbols(path, tag, at):
    """The lines that say where an authored name falls, beside the lifted ones.

    A name of ours belongs to the language rather than to an object, so it is
    recorded against no object at all and any rule may hold it. Anything
    already recorded that way is replaced, which is what makes this safe to
    run again.
    """
    store = STORE % tag
    kept = [line.rstrip("\n") for line in open(path)
            if line.split()[:1] != ["store"] or line.split()[1] != store]
    kept = [line for line in kept
            if line.split()[:2] != ["at", ANY]]
    out = kept
    if at:
        out = out + ["", "# And the constants of our own, out of"
                         " rules/constants by tools/delta-consts.py.",
                     "store %s" % store]
        out += ["at %s %s %s %d" % (ANY, name, store, off)
                for name, off in at]
    open(path, "w").write("\n".join(out).rstrip("\n") + "\n")


def one(tag):
    lang = os.path.join(ROOT, "lang", tag)
    if not os.path.isdir(lang):
        print("consts: there is no lang/%s" % tag)
        return False
    source = os.path.join(lang, "rules", "constants")
    constants = read_constants(source) if os.path.exists(source) else []
    at = write_store(tag, os.path.join(lang, "delta_authored_%s.c" % tag),
                     constants)
    symbols = os.path.join(lang, "rules", "symbols")
    if os.path.exists(symbols):
        write_symbols(symbols, tag, at)
    print("%s: %d constants, %d bytes"
          % (tag, len(constants), sum(len(d) for _n, d in constants)))
    return True


def main(argv):
    if not argv:
        print(__doc__.strip())
        return 2
    ok = True
    for tag in argv:
        try:
            ok = one(tag) and ok
        except ValueError as e:
            print("consts: %s" % e)
            ok = False
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
