#!/usr/bin/env python3
"""A language's built-in settings, out of the object that carries them.

The engine runs on settings compiled into the image rather than on a file:
sections in square brackets, key equals value lines under them, separated by a
nought rather than a newline. `[LanguageIndependent]' names the filters, and
then one section per language gives its voices, its phoneme durations and the
name of the module it came from.

Every language module ships its own `eci.obj' with its own copy, which is why
this can be done at all: the eight voices and the phoneme table in the German
module are German. `eci_register.c' says why the file the original writes is
not reproduced -- nothing in a speaking engine reads it back, and the settings
it runs on are these.

usage: gen-ini.py analysis/dede lang/dede/eci_ini_dede.c
"""

import importlib.util
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

spec = importlib.util.spec_from_file_location(
    "delta_link", os.path.join(ROOT, "tools", "delta-link.py"))
dlk = importlib.util.module_from_spec(spec)
spec.loader.exec_module(dlk)

# What the C++ compiler called them. Both are const, so both are read-only
# data; the size is an int beside the bytes rather than a terminator, because
# the text has noughts all through it.
INI = "?eciIni@@3QBDB"
SIZE = "?eciIniSize@@3HB"


def carrier(where):
    """Which object holds the settings. It is engarray.obj in every module
    seen so far, but looked for rather than assumed: an object that merely
    mentions the symbol is not the one that defines it, and that distinction
    cost a wrong answer once already."""
    import subprocess
    for f in sorted(os.listdir(where)):
        if not f.endswith(".obj"):
            continue
        try:
            out = subprocess.run(["llvm-nm", os.path.join(where, f)],
                                 check=True, capture_output=True,
                                 text=True).stdout
        except Exception:
            continue
        for line in out.splitlines():
            w = line.split()
            # A definition has an address and a section letter; a reference is
            # `U' with no address.
            if len(w) == 3 and w[1] != "U" and w[2] == INI:
                return f
    raise SystemExit("gen-ini: nothing in %s defines %s" % (where, INI))


def read(where):
    o = dlk.Coff(os.path.join(where, carrier(where)))
    for want in (INI, SIZE):
        if want not in o.symbol:
            raise SystemExit("gen-ini: %s has no %s" % (o.path, want))

    sec, at = o.symbol[SIZE]
    raw = o.section[sec][at:at + 4]
    size = int.from_bytes(raw, "little")

    sec, at = o.symbol[INI]
    body = o.section[sec][at:at + size]
    if len(body) != size:
        raise SystemExit("gen-ini: %s says %d bytes and has %d"
                         % (o.path, size, len(body)))
    return body


def write(body, out, lang):
    with open(out, "w") as f:
        f.write("/* The engine's settings for %s, built into the image.\n"
                " *\n"
                " * Generated by tools/gen-ini.py out of the language's own\n"
                " * eci.obj. Sections in square brackets, key equals value\n"
                " * lines under them, and a byte of 0xff on the end. Lines are\n"
                " * separated by a nought rather than a newline, which is why\n"
                " * the reader in eci_iniread.c stops on either.\n"
                " *\n"
                " * Taken byte for byte rather than retyped, because the\n"
                " * reader's arithmetic depends on the exact separators.\n"
                " */\n"
                "\n#include <stdint.h>\n"
                "#include \"eci_synththread.h\"\n"
                "#include \"evv_abi.h\"\n"
                "\n" % lang)
        f.write("const char eciIni[%d] = {\n" % len(body))
        for i in range(0, len(body), 16):
            f.write("    " + ", ".join("%d" % b for b in body[i:i + 16])
                    + ",\n")
        f.write("};\n\n")
        f.write("const int32_t eciIniSize = %d;\n\n" % len(body))
        # Which language this library is. The engine array answers a library
        # name for one language only, and which one is a property of the module
        # that was linked rather than of the engine: the settings above say it
        # in their own section heading, so it is taken from there.
        major, minor = language_of(body)
        f.write("/* The language this module is: [%d.%d] in the settings\n"
                "   above, packed the way the engine holds one. */\n"
                % (major, minor))
        f.write("const int32_t evvLibraryLang = 0x%x;\n"
                % ((major << 16) | minor))


def language_of(body):
    """Which language the settings are for: the one section that is not
    [LanguageIndependent] names it as major.minor."""
    for name in sections(body):
        inner = name[1:-1]
        if inner == "LanguageIndependent":
            continue
        try:
            major, minor = inner.split(".")
            return int(major), int(minor)
        except ValueError:
            continue
    raise SystemExit("gen-ini: the settings name no language")


def sections(body):
    """What the settings say they are for, which is worth printing: a language
    that lifted cleanly and has no section of its own would build and then
    refuse to make an instance."""
    text = body.replace(b"\x00", b"\n").decode("latin-1")
    return [l.strip() for l in text.split("\n")
            if l.startswith("[") and l.endswith("]")]


def main():
    if len(sys.argv) != 3:
        print(__doc__.strip())
        return 2
    where, out = sys.argv[1], sys.argv[2]
    lang = os.path.basename(where)
    body = read(where)
    write(body, out, lang)
    print("%s: %d bytes, sections %s"
          % (lang, len(body), " ".join(sections(body))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
